Vingette for step by step guide how to perform t-test.
Olink-Proteomics/OlinkRPackage pull request #286
Opened 2023-08-22 09:41 UTC by Orbmac

# Title: Write a very short summary here
**Problem:** Write a description of your problem here.

**Solution:** Write a short summary of your solution.

**Key Features:**

* Key feature 1
* Key feature 2
* ...

## Checklist
- [x] Make sure you are requesting to **pull a feature/bugfix branch** (right side). This should not be main or develop.
- [x] Make sure you are make a pull request against either **main or develop** (left side). (Requesting to main should be reserved for bugfixes and new releases)
- [ ] Add or update unit tests (if applicable)
- [ ] Check your code with any unit tests (Run devtools::check() locally)
- [ ] Add neccessary documentation (if applicable)

## Type of changes

What type of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue) (link the issue on the right)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [X] Documentation Update 
- [ ] Other (explain)

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, any questions you have, etc...

Consider linking any issues (#issue-number ) or adding @mentions to ensure specific people see it.

2023-08-25 19:58 UTC, kathy-nevola commented
Maybe add paired t-test vs unpaired t-test or will that be a separate vignette?

2023-08-25 20:00 UTC, kathy-nevola commented
@Orbmac made some edits to clarify the wording, let me know if this makes sense to you. Im struggling to figure out how references work in vignettes and I cant make figure captions work, so if you can help with those issues that would be great,

2023-08-29 13:05 UTC, kathy-nevola commented
Suggestion from user regarding clarity using function: specific pair_id column format and the fact that each group needed at least 16 samples

2023-10-05 15:36 UTC, kathy-nevola requested changes

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_2groups.Rmd
> +This vignette is designed to assist users working with two distinct groups using t-test. This guide aims to provide you with a comprehensive overview of the steps involved in analyzing and comparing
```suggestion
This vignette is designed to assist users working with two distinct groups using t-test. This guide aims to provide you with a comprehensive overview of the steps involved in analyzing and comparing data from two groups in Olink data using Olink's R package, Olink Analyze. These two groups can encompass a variety of categories, such as healthy and diseased individuals, two different types of a condition, or male and female subjects. The objective of the analysis is to identify the differing proteins between the two groups.
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_2groups.Rmd
> +If you have more that two groups in your data, or a longitudinal study see our other study design vignettes.
```suggestion
If you have more that two groups in your data, or a longitudinal study, see our other study design vignettes. 
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_2groups.Rmd
> +This vignette will help you if you have Olink data and are unsure on how to compare your two groups. The Olink data file shouldn't be tempered with before loading it into R, as that may cause the dat
```suggestion
This vignette will help you if you have Olink data and are unsure on how to compare your two groups. The Olink data file shouldn't be tempered with before loading it into R, as that may cause the data to not be recognized and loaded by the `read_NPX` function. Using the read_NPX function will always give you your data in a long format, where each row represent one sample and one protein. To load in your data in R, use the following code:
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_2groups.Rmd
> +# Argument should be the location of your NPX data. Data are usually in parquet, csv, xlsx or zip format depending on the product.
```suggestion
# Argument should be the location of your NPX data. 
# Data are usually in parquet, csv, xlsx or zip format. 
# The file format will depend on the product.
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_3groups.Rmd
> +This vignette is designed to assist users working with 3 or more distinct groups using ANOVA. This guide aims to provide you with a comprehensive overview of the steps involved in analyzing and compa
```suggestion
This vignette is designed to assist users working with 3 or more distinct groups using ANOVA. This guide aims to provide you with a comprehensive overview of the steps involved in analyzing and comparing data from multiple groups in Olink data using Olink's R package, Olink Analyze.  These groups can encompass a variety of categories, such as disease subtypes, treatment regimens, or genetic variations. The objective of the analysis is to identify proteins whose expressions differ between at least 2 of the groups. 
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_3groups.Rmd
> +# Argument should be the location of your NPX data. Data are usually in parquet, csv, xlsx or zip format depending on the product.
```suggestion
# Argument should be the location of your NPX data. 
# Data are usually in parquet, csv, xlsx or zip format.
# The data format depends on the product.
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_3groups.Rmd
> +To illustrate the results from a ANOVA boxplots are a very effective way. These visualizations provide valuable insights into the differences between the groups groups and help in understanding the s
```suggestion
Boxplots are a very effective way to illustrate the results from an ANOVA. These visualizations provide valuable insights into the differences between the groups and help in understanding the significance and effect sizes of the observed effects.
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_3groups.Rmd
> +To generate boxplots the `olink_boxplot` function can be used. The thick black horizontal line within each box indicates the median, the colored area - the interquartile range, the ends of the vertic
```suggestion
To generate boxplots, the `olink_boxplot` function can be used. The thick black horizontal line within each box indicates the median, the colored area - the interquartile range, the ends of the vertical middle line represent the minimum and the maximum values, and the black dots indicate potential assay outliers (beyond the minumum or maximum valuses). Boxplots of the top 6 significant proteins are plotted in **Figure 3**. 
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_3groups.Rmd
> +            paste0('ANOVAResults.csv'),
do we need the paste0 here?

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_3groups.Rmd
> +            paste0('ANOVA_PostHoc_Results.csv'),
same here. is paste0 needed?

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_mixedmodel.Rmd
> +This vignette is designed to assist users working with longitudinal samples divided across multiple groups using linear mixed models. This guide aims to provide you with a comprehensive overview of t
```suggestion
This vignette is designed to assist users working with longitudinal samples divided across multiple groups using linear mixed models. This guide aims to provide you with a comprehensive overview of the steps involved in analyzing Olink data when the samples are measured over time in different groups using Olink's R package, Olink Analyze. An example can be samples measured over time where half the subjects have been revived a treatment and the other half have not. 
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_mixedmodel.Rmd
> +# Argument should be the location of your NPX data. Data are usually in parquet, csv, xlsx or zip format depending on the product.
```suggestion
# Argument should be the location of your NPX data. 
# Data are usually in parquet, csv, xlsx or zip format.
# Data file format depends on the product.
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_mixedmodel.Rmd
> +LMM assesses the null hypothesis that no significant effect of the independent variables on the dependent variable. If the p-value associated with the test is lower than a predetermined significance
```suggestion
LMM assesses the null hypothesis that there is no significant effect of the independent variables on the dependent variable. If the p-value associated with the test is lower than a predetermined significance level (typically 0.05), we can reject the null hypothesis and infer a significant effect of at least one independent variable on the dependent variable. This indicates that the independent variables, included in the model, have a statistically significant impact on explaining the variation in the dependent variable.
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_mixedmodel.Rmd
> +The LMM also take into account the random effect, which is a critical component of the model. Random effects are used to model the variability within groups or clusters in the data, accounting for co
```suggestion
The LMM also take into account the random effect, which is a critical component of the model. Random effects are used to model the variability within groups or clusters in the data, accounting for correlations and hierarchical structures that might exist. These random effects are essential in capturing the dependencies and correlations in the data that cannot be explained solely by the independent variables. The random effect is usually within subject correlation for Olink studies. 
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_mixedmodel.Rmd
> +               caption = "**Table 4.** ANOVA post hoc results of the 5 most significant contrasts and proteins. Some coloumns have been left out due to space.",
```suggestion
               caption = "**Table 4.** ANOVA post hoc results of the 5 most significant contrasts and proteins. Some columns have been left out due to space.",
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_mixedmodel.Rmd
> +To illustrate the results from a LMM a point range plot are a common way. These visualizations provide valuable insights into the differences between the groups and help in understanding the signific
```suggestion
A point range plot is a common way to illustrate the results from an LMM. These visualizations provide valuable insights into the differences between the groups and help in understanding the significance and effect sizes of the observed effects.
```

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_mixedmodel.Rmd
> +            paste0('LMER_Results.csv'),
same question as before with paste0

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_mixedmodel.Rmd
> +```
Add contact us section

2023-10-05 15:36 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_mixedmodel.Rmd
> +write.table(lmer_posthoc_results_Time, # each term should be saved
same question with paste0

2023-10-05 15:38 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_mixedmodel.Rmd
> +  %\VignetteIndexEntry{Olink® Analyze Vignette}
```suggestion
  %\VignetteIndexEntry{A Guide to Comparative Analysis of longitudinal data across multiple groups}
```

2023-10-05 15:39 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_mixedmodel.Rmd
> +title: "A Guide to Comparative Analysis of logitudinal data across muliple groups"
```suggestion
title: "A Guide to Comparative Analysis of longitudinal data across multiple groups"
```

2023-10-05 15:39 UTC, kathy-nevola commented on OlinkAnalyze/vignettes/study_design_3groups.Rmd
> +  %\VignetteIndexEntry{A Guide to Comparative Analysis of Muliple Groups with Olink Data}
```suggestion
  %\VignetteIndexEntry{A Guide to Comparative Analysis of Multiple Groups with Olink Data}
```

2023-10-16 08:23 UTC, Orbmac reviewed
All changed added

2023-10-23 12:44 UTC, kathy-nevola approved these changes
LGTM

2024-04-30 17:20 UTC, closed without merging