code updated
Olink-Proteomics/OlinkRPackage pull request #428
Opened 2024-08-19 10:29 UTC by boxizhang

# Title: Codes update
**Problem:** Write a description of your problem here.

**Solution:** Write a short summary of your solution.

**Key Features:**

* Key feature 1
* Key feature 2
* ...

## Checklist
- [ ] Make sure you are requesting to **pull a feature/bugfix branch** (right side). This should not be main or develop.
- [X] Make sure you are make a pull request against either **main or develop** (left side). (Requesting to main should be reserved for bugfixes and new releases)
- [ ] Add or update unit tests (if applicable)
- [ ] Check your code with any unit tests (Run devtools::check() locally)
- [X] Add neccessary documentation (if applicable)

## Type of changes

What type of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue) (link the issue on the right)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [X] Documentation Update 
- [ ] Other (explain)

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, any questions you have, etc...

Consider linking any issues (#issue-number ) or adding @mentions to ensure specific people see it.

2024-08-20 19:31 UTC, dtopouza requested changes
Some code edits to be addressed.

2024-08-21 08:58 UTC, boxizhang commented on OlinkAnalyze/vignettes/bridging_E3072toEHT.Rmd
> +data.frame(SampleID = intersect(data_E3072$SampleID, data_EHT$SampleID)) %>%
I added that because we do not have the example data yet. We need to update that after we have the example data.

2024-08-21 09:18 UTC, boxizhang commented on OlinkAnalyze/vignettes/bridging_E3072toEHT.Rmd
I don't think we should change the SampleID, so I put  npx_br_data here.

2024-08-21 13:20 UTC, dtopouza commented on OlinkAnalyze/vignettes/bridging_E3072toEHT.Rmd
That sounds good!

2024-08-21 13:22 UTC, dtopouza approved these changes

2024-08-22 14:45 UTC, merged