3k-HT median normalization using bridge samples
Olink-Proteomics/OlinkRPackage pull request #440
Opened 2024-09-03 18:15 UTC by klevdiamanti

# Title: Normalization between Olink Explore HT and Olink Explore 3072 data using bridge samples
**Problem:** All bridge normalization between Olink Explore HT and Olink Explore 3072 data using a set of bridge samples to compute the median of the pairwise differences to estimate technical differences.

**Solution:** Create an internal function that utilizes the existing bridge normalization function to allow this cross-product normalization.

**Key Features:**

* Automatically identify 3K and HT data from inputs.
* Adjust current checks on data for normalization to 3K and HT datasets.
* Add matched identifiers of Olink assays from each dataset to the input datasets.
* Check that HT dataset is always the reference dataset.
* Update documentation of relevant functions.

## Checklist
- [X] Make sure you are requesting to **pull a feature/bugfix branch** (right side). This should not be main or develop.
- [X] Make sure you are make a pull request against either **main or develop** (left side). (Requesting to main should be reserved for bugfixes and new releases)
- [X] Add or update unit tests (if applicable)
- [X] Check your code with any unit tests (Run devtools::check() locally)
- [X] Add neccessary documentation (if applicable)

## Type of changes

What type of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue) (link the issue on the right)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [X] Documentation Update 
- [ ] Other (explain)

## Further comments
Datasets provided as input in the olink_normalization function are extensively checked before the normalization is performed. In order to allow for cross-product normalization we had to adjust these checks so that only relevant checks are performed. In addition, because all the downstream functions require shared identifiers of Olink assays between the datasets that are to be normalized, we used the internal dataset eHT_e3k_mapping to add the concatenated identifiers of the two platforms as the new OlinkID. This intermediate Olink identifier will be used to allow normalization, and eventually removed prior to reporting the normalized dataset back to the customer.

A new function olink_normalization_bridge_product will be added once the features is_bridgeable (#438) and qq_normalization (#439) are merged into develop_4.0.

2024-09-03 20:25 UTC, kristynchin-olink commented on OlinkAnalyze/R/globals.R
These lines have been moved to OlinkAnalyze/data-raw/normalization_utils.R

2024-09-04 15:59 UTC, kristynchin-olink commented on OlinkAnalyze/tests/testthat/test-olink_normalization_utils.R
Confirm that all cross-platform normalization tests pass

2024-09-04 16:15 UTC, kristynchin-olink commented on OlinkAnalyze/R/olink_normalization_utils.R
Getting error on if statement in lines 920-921: 

  if (norm_mode == olink_norm_modes$norm_ht_3k && 
      **names(lst_product)[names(lst_product) == "HT"] != reference_project**)

The highlighted portion returns character(0) which throws an error. If we replace with the following, the script works as expected:

  if (norm_mode == olink_norm_modes$norm_ht_3k && 
      **names(lst_product)[lst_product == "HT"] != reference_project**)

2024-09-04 16:26 UTC, kristynchin-olink commented on OlinkAnalyze/R/olink_normalization.R
Error from 502-508 caused by binding of DFs. HT 'Block' column is numeric and 3K 'Block' column is character. If we mutate Block from numeric to character in 3K-HT normalization, this resolves the issue. 

Not sure where the best location to do this would be - olink_normalization_utils or in the olink_normalization script itself??

2024-09-04 16:36 UTC, kristynchin-olink commented on OlinkAnalyze/R/olink_normalization.R
Noticed that the final output from olink_normalization for 3K-HT normalization needs to be slightly modified:

- Need to add a MedianNormNPX column with the adjusted NPX value
- Remove the Adj_factor column from the final output
- NPX column should reflect the original NPX (i.e. without adjustment)

Potential steps for achieving the above:
1. Mutate DF, copying 'NPX' column as 'MedianNormNPX'
2. Mutate DF to subtract the 'Adj_factor' value from the 'NPX' value to re-establish the unadjusted NPX
3. Deselect the Adj_factor column to remove from the DF

2024-09-04 16:38 UTC, kristynchin-olink requested changes
I've loaded the modified files and run the testthat script locally. I have also attempted running olink_normalization locally and identified some small errors in the olink_normalization_utils and olink_normalization function with proposed changes.

2024-09-05 09:16 UTC, klevdiamanti commented on OlinkAnalyze/R/olink_normalization_utils.R
Thanks for catching this Kristyn. I also added it in the tests. It's fixed now.

2024-09-05 14:38 UTC, kristynchin-olink commented on OlinkAnalyze/R/sysdata.rda
Confirming that Block_HT from eHT_e3072_mapping DF is a character vector as expected.

2024-09-05 14:39 UTC, kristynchin-olink commented on OlinkAnalyze/data-raw/mapping.R
Confirming that Block_HT from eHT_e3072_mapping DF is a character vector as expected. Looks good.

2024-09-05 17:05 UTC, kristynchin-olink commented on OlinkAnalyze/R/olink_normalization.R
Noted. Will wait for wait for integration implementation before addressing final output format.

2024-09-05 17:06 UTC, kristynchin-olink approved these changes
All changes look good. Confirmed that final output formatting will be addressed during bridgeability-mediannorm-QSnorm function integration implementation.

2024-09-05 17:37 UTC, merged